services:
  master1:
    build: 
      context: .
    hostname: master1
    container_name: m1
    ports:
      - "9180:8088"
      - "9885:9870"
    networks:
      - hd_net
    healthcheck:
      test: ["CMD", "hdfs", "haadmin", "-checkHealth", "nn1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - nn1:/usr/local/hadoop/hdfs/namenode
      - jn1:/usr/local/hadoop/hdfs/journals
      - zk1:/usr/local/zookeeper/data
  master2:
    build: 
      context: .
    hostname: master2
    container_name: master2
    ports:
      - "9280:8088"
      - "9886:9870"
    networks:
      - hd_net
    volumes:
      - nn2:/usr/local/hadoop/hdfs/namenode
      - jn2:/usr/local/hadoop/hdfs/journals
      - zk2:/usr/local/zookeeper/data
  master3:
    build: 
      context: .
    hostname: master3
    container_name: master3 
    ports:
      - "9380:8088"
      - "9887:9870"
    networks:
      - hd_net
    volumes:
      - nn3:/usr/local/hadoop/hdfs/namenode
      - jn3:/usr/local/hadoop/hdfs/journals
      - zk3:/usr/local/zookeeper/data
  worker: 
    build: 
      context: .
    hostname: worker
    container_name: worker
    depends_on:
      master1: 
        condition: service_healthy
    networks:
        - hd_net
    volumes:
      - dn1:/usr/local/hadoop/hdfs/datanode


volumes:
  nn1:
  nn2:
  nn3:
  jn1:
  jn2:
  jn3:
  dn1:
  zk1:
  zk2:
  zk3:
    
networks:
  hd_net:


